const els = { session: document.querySelector('#session-card'), kpis: document.querySelector('#kpis'), students: document.querySelector('#students-output'), chart: document.querySelector('#chart'), detail: document.querySelector('#detail-output'), my: document.querySelector('#my-output'), search: document.querySelector('#search'), refresh: document.querySelector('#refresh'), loadMy: document.querySelector('#load-my') };
function safe(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
async function api(path, options={}){const res=await fetch(path,{cache:'no-store',credentials:'include',headers:{'content-type':'application/json',...(options.headers||{})},...options});const text=await res.text();const data=text?JSON.parse(text):{};if(!res.ok)throw new Error(data.mensagem||data.erro||`HTTP ${res.status}`);return data}
function kpi(label,value,detail){return `<div class="fc-kpi"><small>${safe(label)}</small><strong>${safe(value)}</strong><span>${safe(detail)}</span></div>`}
async function session(){try{const data=await api(`/api/mvp-15/session?v=${Date.now()}`);const s=data.current_session;if(!s){els.session.innerHTML='<strong>Login necessário</strong><span>Entre para ver evolução.</span><a class="button secondary" href="/mvp-19.html">Entrar</a>';return null}els.session.innerHTML=`<strong>${safe(s.actor_role)} · ${safe(s.actor_name)}</strong><span>unidade ${safe(s.tenant_slug)} · acesso confirmado</span>`;return s}catch(e){els.session.innerHTML=`<strong>Erro</strong><span>${safe(e.message)}</span>`;return null}}
function renderKpis(summary={}){els.kpis.innerHTML=[kpi('Alunos',summary.students??0,'com execução registrada'),kpi('Execuções',summary.executions??0,'histórico do tenant'),kpi('Concluídos',summary.completed??0,'treinos finalizados'),kpi('Esforço médio',summary.average_effort??'-','escala 1–10')].join('')}
function renderChart(weekly=[]){const max=Math.max(1,...weekly.map(w=>Number(w.executions||0)));els.chart.innerHTML=weekly.length?weekly.map(w=>`<div class="fc-bar" style="height:${Math.max(12,(Number(w.executions||0)/max)*100)}%"><span>${safe(w.executions)}</span></div>`).join(''):'<span>Sem histórico semanal ainda.</span>'}
function renderStudents(data){const items=data.students||[];els.students.innerHTML=items.length?items.map(s=>`<div class="item student-card"><div><span class="badge">${safe(s.progress_percent)}%</span><strong>${safe(s.student_name)}</strong><span>${safe(s.total_executions)} execuções · ${safe(s.completed_executions)} concluídas · esforço ${safe(s.average_effort??'-')}/10</span><div class="progress-line"><span style="width:${Math.min(100,Number(s.progress_percent||0))}%"></span></div><small>professor: ${safe(s.professor_name||'não definido')} · frequência 7d: ${safe(s.weekly_frequency)}</small></div><button type="button" data-student-id="${safe(s.student_id)}">Ver histórico</button></div>`).join(''):'<div class="item">Nenhum aluno com execução encontrada.</div>'}
function renderDetail(data,target=els.detail){const s=data.student;const history=data.history||[];target.innerHTML=`<strong>${safe(s.student_name)}</strong><span>${safe(s.total_executions)} execuções · ${safe(s.completed_executions)} concluídas · ${safe(s.weekly_frequency)} na semana</span><span>Esforço médio ${safe(s.average_effort??'-')}/10 · duração média ${safe(s.average_duration??'-')} min</span>`+history.map(h=>`<div class="history-row"><strong>${safe(h.nome_treino)}</strong><small>${safe(h.status)}</small><small>${safe(h.progress_percent)}%</small><small>${safe(h.percepcao_esforco??'-')}/10</small><small>${safe(h.duracao_minutos??'-')} min</small></div>`).join('')}
async function loadTenant(){try{const params=new URLSearchParams();if(els.search.value.trim())params.set('search',els.search.value.trim());params.set('limit','60');const data=await api(`/api/mvp-26/evolution?${params.toString()}`);renderKpis(data.summary||{});renderChart(data.weekly||[]);renderStudents(data)}catch(e){els.students.innerHTML=`<div class="item"><strong>Acesso necessário</strong><span>${safe(e.message)}</span><a class="button secondary" href="/mvp-19.html">Entrar</a></div>`}}
async function loadMy(){try{const data=await api('/api/mvp-26/my-evolution?limit=80');renderDetail(data,els.my);renderKpis({students:1,executions:data.student.total_executions,completed:data.student.completed_executions,average_effort:data.student.average_effort});els.detail.innerHTML='Minha evolução carregada no painel à esquerda.'}catch(e){els.my.innerHTML=`<strong>Não carregou</strong><span>${safe(e.message)}</span>`}}
async function loadStudent(id){try{renderDetail(await api(`/api/mvp-26/students/${encodeURIComponent(id)}/evolution?limit=80`))}catch(e){els.detail.innerHTML=`<strong>Erro</strong><span>${safe(e.message)}</span>`}}
els.refresh?.addEventListener('click',loadTenant);els.search?.addEventListener('input',()=>{clearTimeout(window.__fitcoreSearch);window.__fitcoreSearch=setTimeout(loadTenant,250)});els.loadMy?.addEventListener('click',loadMy);els.students?.addEventListener('click',e=>{const btn=e.target.closest('[data-student-id]');if(btn)loadStudent(btn.dataset.studentId)});document.addEventListener('DOMContentLoaded',async()=>{const s=await session();if(s?.actor_role==='aluno')loadMy();else loadTenant()});
